# -*- coding: utf-8 -*-
"""
/***************************************************************************
 eRPTSIntegration
                                 A QGIS plugin
 eRPTS Integration
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-11
        copyright            : (C) 2021 by @seintaxerror
        email                : seintaxerror@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load eRPTSIntegration class from file eRPTSIntegration.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .zds_erpts_integration import eRPTSIntegration
    return eRPTSIntegration(iface)
